name: Preprocessing Pipeline

on:
  push:
    paths:
      - 'Preprocessing/preprocessing.py'
      - 'Preprocessing/flood_preprocessing.csv'
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run preprocessing
        run: python Preprocessing/preprocessing.py flood/train.csv Preprocessing/flood_preprocessing.csv